export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const DELETE_TODO = 'DELETE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const DELETE_ALL_COMPLETED = 'DELETE_ALL_COMPLETED';
export const COMPLETE_ALL = 'COMPLETE_ALL';